[package]
name = "rustory"
version = "1.0.5"
edition = "2024"
autobins = false

[[bin]]
name = "rr"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.6", features = ["derive"] }
ctrlc = "3.5"
futures = "0.3"
libp2p-core = "0.43"
libp2p-dcutr = "0.14"
libp2p-identify = "0.47"
libp2p-identity = { version = "0.2", features = ["ed25519", "peerid", "rand"] }
libp2p-mplex = "0.43"
libp2p-noise = "0.46"
libp2p-ping = "0.47"
libp2p-pnet = "0.26"
libp2p-relay = "0.21"
libp2p-request-response = { version = "0.29", features = ["json"] }
libp2p-swarm = { version = "0.47", features = ["macros", "tokio"] }
libp2p-tcp = { version = "0.44", features = ["tokio"] }
libc = "0.2"
multiaddr = "0.18"
rand = "0.10"
regex = "1.12"
rusqlite = { version = "0.40", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tiny_http = "0.12"
time = { version = "0.3", features = ["serde", "macros"] }
tokio = { version = "1", features = ["rt", "macros", "time", "sync"] }
toml = "1.1"
unicode-width = "0.2"
ureq = "3.3"
urlencoding = "2.1"
uuid = { version = "1.23", features = ["v4", "v5", "serde"] }
zstd = "0.13"

[dev-dependencies]
tempfile = "3.27"
